### ISSUE TITLE
Wrong type for KeyboardButtonRequestUsers.max_quantity

### ISSUE THREAD

**Issue by ubertao** [grammyjs/types#36]
https://github.com/grammyjs/types/blob/e266fb129062d48fd82a16a374ad7f6ec080a868/markup.ts#L234C26-L234C26

```typescript
export interface KeyboardButtonRequestUsers {
  ...
  max_quantity?: boolean; // <-- should be number
}
```

**Comment by KnorpelSenf** [comment]
Damn it, thanks for pointing it out. I'll release a fix in a few hours.
